%SKELETON
{% macro authoritativeDefinitions(field) %}
{% if field | length > 0 %}
authoritativeDefinitions: {% for item in field %}
- url: ${{ item.urlAuthoritative | dump }}
  type: ${{ item.typeAuthoritative | dump }}
{% endfor %}
{% endif %}
{% endmacro %}

{# {% macro customProperty(field) %}
{% if field | length > 0 %}
customProperties: {% for item in field %}
- property: ${{ item.customProperty | dump }}
  value: ${{ item.customValue | dump }}
{% endfor %}
{% endif %}
{% endmacro %} #}

{% macro quality(field) %}
{% for quality in field %}
- name: ${{ quality.nameQuality | dump }}
  type: ${{ quality.typeQuality | dump }}
  description: ${{ quality.descriptionQuality | dump }}
  dimension: ${{ quality.dimension | dump }}
  severity: ${{ quality.severity | dump }}
  businessImpact: ${{ quality.businessImpact | dump }}
  {# custom properties #}
  {# ${{ customProperty(quality.qualityCustomProperties) | indent(18, true)}} #}
  tags: {% if quality.qualityTags | length > 0 %}${{ quality.qualityTags | dump }}{% else %}[]{% endif %}
  authoritativeDefinitions: {% for item in quality.authoritativeDefinitionsQuality %}
  - url: ${{ item.urlAuthoritative | dump }}
    type: ${{ item.typeAuthoritative | dump }}
  {% endfor %}
  scheduler: ${{ quality.scheduler | dump }}
  schedule: ${{ quality.schedule | dump }}
  {% if quality.typeQuality == "sql" %}
  query: |
    ${{ quality.propertyType.query }}
  {% if "mustBe" in quality.propertyType.operators%}mustBe: ${{quality.propertyType.valueMustBe | dump }}{% endif %}
  {% if "mustNotBe" in quality.propertyType.operators%}mustNotBe: ${{quality.propertyType.valueMustNotBe | dump }}{% endif %}
  {% if "mustBeBetween" in quality.propertyType.operators%}mustBeBetween: [${{quality.propertyType.valueRange1Between | dump }}, ${{quality.propertyType.valueRange2Between | dump }}]{% endif %}
  {% if "mustNotBeBetween" in quality.propertyType.operators%}mustNotBeBetween: [${{quality.propertyType.valueRange1BetweenNot | dump }}, ${{quality.propertyType.valueRange2BetweenNot | dump }}]{% endif %}
  {% if "mustBeGreaterThan" in quality.propertyType.operators%}mustBeGreaterThan: ${{quality.propertyType.valueMustBeGreaterThan | dump }}{% endif %}
  {% if "mustBeGreaterOrEqualTo" in quality.propertyType.operators%}mustBeGreaterOrEqualTo: ${{quality.propertyType.valueMustBeGreaterOrEqualTo | dump }}{% endif %}
  {% if "mustBeLessThan" in quality.propertyType.operators%}mustBeLessThan: ${{quality.propertyType.valueMustBeLessThan | dump }}{% endif %}
  {% if "mustBeLessOrEqualTo" in quality.propertyType.operators%}mustBeLessOrEqualTo: ${{quality.propertyType.valueMustBeLessOrEqualTo | dump }}{% endif %}
  {% endif %}
  {% if quality.typeQuality == "custom" %}
  engine: ${{ quality.propertyType.engine | dump }}
  {% if quality.propertyType.engine == "great expectations" %}
  {% set exp = quality.propertyType.greatExpectations %}
  implementation: |
    expectation_type: ${{ exp.expectation_type }}
    column: ${{ exp.column }}
    {% if exp.min_value is defined %}min_value: ${{ exp.min_value }}
    {% endif -%}{% if exp.max_value is defined %}max_value: ${{ exp.max_value }}
    {% endif -%}{% if exp.strict_min is defined %}strict_min: ${{ exp.strict_min }}
    {% endif -%}{% if exp.strict_max is defined %}strict_max: ${{ exp.strict_max }}
    {% endif -%}{% if exp.value_set[0] %}value_set: ${{ exp.value_set | dump }}
    {% endif -%}{% if exp.regex is defined %}regex: ${{ exp.regex }}
    {% endif -%}
  {% endif %}
  {% endif %}
{% endfor %}
{% endmacro %}

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.identifier }}
  version: ${{ values.identifier.split(".")[2] + ".0.0" }}
  description: ${{ values.description | dump }}
  tags: [data-contract, bitol, outputport]
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: outputport
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
  system: ${{ values.dataproduct | dump }}
  domain: ${{ values.domain | dump }}
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  mesh:
    name: ${{ values.name | dump }}
    description: ${{ values.description | dump }}
    kind: outputport
    infrastructureTemplateId: urn:dmb:itm:data-contract-bitol-tech-adapter:1
    useCaseTemplateId: ${{ values.useCaseTemplateId }}
    __dataContractEnabled: true
    dependsOn: {% if values.dependsOn | length > 0 %}{% for i in values.dependsOn %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    specific: {}
    dataContract:
      domain: ${{ values.domain | dump }}
      dataProduct: ${{ values.dataproduct | dump }}
      name: ${{ values.nameDC | dump }}
      description:
        purpose: ${{ values.purpose | dump }}
        limitation: ${{ values.limitation | dump }}
        usage: ${{ values.usage | dump }}
        ${{ authoritativeDefinitions(values.authoritativeDefinitionsDescription) | indent(8, true)}}
        {# custom properties #}
        {# ${{ customProperty(values.descriptionCustomProperties) | indent(8, true)}} #}
      tenant: ${{ values.tenant | dump }}
      tags: {% if values.tags | length > 0 %}${{ values.tags | dump }}{% else %}[]{% endif %}
      kind: DataContract
      {% if values.status == "other" %}
      status: ${{ values.otherStatus | dump }}
      {% else %}
      status: ${{ values.status | dump }}
      {% endif %}
      ${{ authoritativeDefinitions(values.authoritativeDefinitions) | indent(6, true)}}
      schema:
      {% for schema in values.schemas.elements %}
        - name: ${{ schema.elementName | dump }}
          logicalType: object
          description: ${{ schema.elementDescription | dump }}
          businessName: ${{ schema.businessName | dump }}
          ${{ authoritativeDefinitions(schema.authoritativeDefinitionsSchema) | indent(10, true)}}
          tags: {% if values.schemaTags | length > 0 %}${{ values.schemaTags | dump }}{% else %}[]{% endif %}
          dataGranularityDescription: ${{ schema.dataGranularityDescription | dump }}
          maxProperties: ${{ schema.maxProperties | dump }}
          minProperties: ${{ schema.minProperties | dump }}
          required: ${{ schema.requiredField | dump }}
          properties: {% for property in schema.schemaProperties.tableColumns %}
            - name: ${{ property.elementName | dump }}
              description: ${{ property.elementDescription | dump }}
              businessName: ${{ property.businessName | dump }}
              logicalType: {% if property.logicalType == "" %}null{% else %}${{ property.logicalType | dump }}{% endif %}
              ${{ authoritativeDefinitions(property.authoritativeDefinitionsSchema) | indent(14, true)}}
              tags: {% if property.schemaTags | length > 0 %}${{ property.schemaTags | dump }}{% else %}[]{% endif %}
              dataGranularityDescription: ${{ property.dataGranularityDescription | dump }}
              primaryKey: ${{ property.primaryKey | dump }}
              {% if property.primaryKey %}
              primaryKeyPosition: ${{ property.primaryKeyPosition | dump }}
              {% else %}
              primaryKeyPosition: -1
              {% endif %}
              requiredProperty: ${{ property.requiredProperty | dump }}
              unique: ${{ property.unique | dump }}
              classification: ${{ property.classification | dump }}
              encryptedName: ${{ property.encryptedName | dump }}
              transformSourceObjects: {% for source in property.transformSourceObjects %}
                - ${{ source | dump }}
              {% endfor %}
              examples: {% for example in property.exampleValues %}
                - ${{ example | dump }}
              {% endfor %}
              criticalDataElement: ${{ property.criticalDataElement | dump }}
              {# {% if property.logicalType == "array" %}
              maxItems: ${{ property.logicalTypeOptions.maxItems | dump }}
              minItems: ${{ property.logicalTypeOptions.minItems | dump }}
              uniqueItems: ${{ property.logicalTypeOptions.uniqueItems | dump }}
              items: TODO
              {% endif %} #}
              {% if property.logicalType == "date" %}
              logicalTypeOptions:
                format: ${{ property.logicalTypeOptions.dataFormat | dump }}
                minimum: ${{ property.logicalTypeOptions.dataMinimum | dump }}
                maximum: ${{ property.logicalTypeOptions.dataMaximum | dump }}
                exclusiveMinimum: ${{ property.logicalTypeOptions.dataExclusiveMinimum | dump }}
                exclusiveMaximum: ${{ property.logicalTypeOptions.dataExclusiveMaximum | dump }}
              {% endif %}
              {% if property.logicalType == "number" or property.logicalType == "integer" %}
              logicalTypeOptions:
                format: ${{ property.logicalTypeOptions.numberFormat | dump }}
                minimum: ${{ property.logicalTypeOptions.numberMinimum | dump }}
                maximum: ${{ property.logicalTypeOptions.numberMaximum | dump }}
                exclusiveMinimum: ${{ property.logicalTypeOptions.numberExclusiveMinimum | dump }}
                exclusiveMaximum: ${{ property.logicalTypeOptions.numberExclusiveMaximum | dump }}
                multipleOf: ${{ property.logicalTypeOptions.multipleOf | dump }}
              {% endif %}
              {# {% if property.logicalType == "object" %}
              maxProperties: ${{ property.logicalTypeOptions.maxProperties | dump }}
              minProperties: ${{ property.logicalTypeOptions.minProperties | dump }}
              required: ${{ property.logicalTypeOptions.required | dump }}
              TODO
              {% endif %} #}
              {% if property.logicalType == "string" %}
              logicalTypeOptions:
                format: ${{ property.logicalTypeOptions.stringFormat | dump }}
                pattern: ${{ property.logicalTypeOptions.stringPatterns | dump }}
                maxLength: ${{ property.logicalTypeOptions.maxLength | dump }}
                minLength: ${{ property.logicalTypeOptions.minLength | dump }}
              {% endif %}
              {# custom properties #}
              {# ${{ customProperty(property.columnCustomProperties) | indent(14, true)}} #}
              quality: {% for qualityInfo in values.qualitiesInfo %}
              {% if qualityInfo.nameColumn == property.elementName and qualityInfo.nameTable.label == schema.elementName %}
              ${{ quality(qualityInfo.objQualities.qualities) | indent(16, true)}}
              {% endif %} {% endfor%} {# qualities #}
            {% endfor %} {# properties #}
          quality: {% for qualityInfo in values.qualitiesInfo %}
          {% if not qualityInfo.nameColumn and qualityInfo.nameTable.label == schema.elementName %}
          ${{ quality(qualityInfo.objQualities.qualities) | indent(12, true)}}
          {% endif %} {% endfor %} {# qualities #}
      {% endfor %} {# schema #}
      support: {% for support in values.supports %}
        - channel: ${{ support.channel | dump }}
          url: ${{ support.urlChannel | dump }}
          description: ${{ support.descriptionChannel | dump }}
          scope: ${{ support.scope | dump }}
          invitationUrl: ${{ support.invitationUrl | dump }}
          {% if support.tools == "other" %}
          tools: ${{ support.otherTools | dump }}
          {% else %}
          tools: {% if support.tools == "" %}null{% else %}${{ support.tools | dump }} {% endif %}
          {% endif %}
        {% endfor %}
      price:
        priceAmount: ${{ parameters.priceAmount | dump}}
        priceCurrency: ${{ parameters.priceCurrency | dump}}
        priceUnit: ${{ parameters.priceUnit | dump}}
      slaDefaultElement: ${{ parameters.slaDefaultElement | dump}}
      slaProperties: {% for SLSproperty in values.propertiesSLA %}
        - property: ${{ SLSproperty.propertySLA | dump }}
          value: ${{ SLSproperty.valueSLA | dump }}
          valueExt: ${{ SLSproperty.valueExt | dump }}
          unit: ${{ SLSproperty.unitSLA | dump }}
          element: ${{ SLSproperty.elementSLA | dump }}
          driver: ${{ SLSproperty.driverSLA | dump }}
      {% endfor %}
      {% if values.otherCustomProperties | length > 0 %}
      customProperties: {% for item in values.otherCustomProperties %}
        - property: ${{ item.customProperty | dump }}
          value: ${{ item.customValue | dump }}
      {% endfor %}
      {% endif %}
      contractCreatedTs: ${{ values.contractCreatedTs | dump }}